Adds javadocs to tests
sbowe1/spring-react-project1 pull request #33
Opened 2024-09-07 00:48 UTC by pekellogg

Leverages @DisplayName for Test methods to create a descriptive text of what the method should do. Used this as opposed to javadocs to see message in testing context. Added per Lauren D. recco via Code Review - 2

2024-09-07 03:17 UTC, sbowe1 requested changes

2024-09-07 03:17 UTC, sbowe1 commented on p1-backend/src/test/java/com/example/p1_backend/services/QuestionServiceTest.java
@DisplayName("Update question status to incorrect") -> "Update content of question"

2024-09-07 03:17 UTC, sbowe1 commented on p1-backend/src/test/java/com/example/p1_backend/services/UserServiceTest.java
@DisplayName("Update question status to incorrect") - the result is a new token

2024-09-13 19:30 UTC, pekellogg commented on p1-backend/src/test/java/com/example/p1_backend/services/QuestionServiceTest.java
Made requested change

2024-09-13 19:34 UTC, pekellogg commented on p1-backend/src/test/java/com/example/p1_backend/services/UserServiceTest.java
Looking into this now. Do you recall the method? Text, "Update question status to incorrect" is not found in UserServiceTest.java

2024-09-13 19:47 UTC, pekellogg commented on p1-backend/src/test/java/com/example/p1_backend/services/UserServiceTest.java
UserServiceTest's update method: @DisplayName("Return updated user if exists") -> "Return updated token if user exists"

2024-09-13 19:47 UTC, pekellogg commented on p1-backend/src/test/java/com/example/p1_backend/services/UserServiceTest.java
Resolved via Discord chatter

2024-09-13 19:48 UTC, sbowe1 approved these changes

2024-09-13 19:49 UTC, merged